### PR TITLE
initial commit of README.rst

### PR DESCRIPTION
**Pull request by esc**
This is the initial version of the README.rst. It describes some of the
basics of the project and the beginnings of a usage guide.

### CODE REVIEW

**Comment by esc** [comment]
@jrbourbeau can you review and merge if good?

**Comment by esc** [comment]
It still needs some more fleshing out and details but is a good start I feel.

**Review by jrbourbeau — APPROVED** [review]
This looks good, thanks for adding it @esc! I pushed a few nitpicky edits, hope that's okay. The only edit of substance is updating the link to `dask-integration-testing`, which is still in my account. I want to wait until I've added a few more targets before proposing the move to the Dask org

**Comment by esc** [comment]
@jrbourbeau LGTM, thanks for merge!

**Pull request merged**
